/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.system.monitor;

import oshi.SystemInfo;
import oshi.hardware.CentralProcessor;

/**
 *
 * @author manoel
 */
public class Info extends javax.swing.JPanel {

    SystemInfo si = new SystemInfo();
    CentralProcessor.ProcessorIdentifier cpu = si.getHardware().getProcessor().getProcessorIdentifier();
    
    /**
     * Creates new form Info
     */
    public Info() {
        initComponents();
        
        lblOperatingSystem.setText(si.getOperatingSystem().toString());
        lblCPUName.setText(cpu.getName());
        lblCPUIdentifier.setText(cpu.getIdentifier());
        lblCPUMicroArchtecture.setText(cpu.getMicroarchitecture());
        lblCPUVendor.setText(cpu.getVendor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblOperatingSystem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCPUName = new javax.swing.JLabel();
        lblCPUIdentifier = new javax.swing.JLabel();
        lblCPUMicroArchtecture = new javax.swing.JLabel();
        lblCPUVendor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("INFORMACOES DO SISTEMA:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        lblOperatingSystem.setText(":");
        add(lblOperatingSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 510, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Processador:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblCPUName.setText(":");
        add(lblCPUName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 450, 20));

        lblCPUIdentifier.setText(":");
        add(lblCPUIdentifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 450, -1));

        lblCPUMicroArchtecture.setText(":");
        add(lblCPUMicroArchtecture, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 450, -1));

        lblCPUVendor.setText(":");
        add(lblCPUVendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 450, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Sistema Operacional:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCPUIdentifier;
    private javax.swing.JLabel lblCPUMicroArchtecture;
    private javax.swing.JLabel lblCPUName;
    private javax.swing.JLabel lblCPUVendor;
    private javax.swing.JLabel lblOperatingSystem;
    // End of variables declaration//GEN-END:variables
}
