/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.system.monitor;

import com.mycompany.system.monitor.api.CPU;
import com.mycompany.system.monitor.api.Disk;
import com.mycompany.system.monitor.api.RAM;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author mayara
 */
public class Dashboard extends javax.swing.JFrame {
        private CPU cpu = new CPU();
    private RAM ram = new RAM();
    private Disk disk = new Disk();
    /**
     * Creates new form Dashboard
     */
  
   
    public Dashboard() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAnalisarComponentes = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblRam2 = new javax.swing.JLabel();
        lblPid2 = new javax.swing.JLabel();
        lblCpu3 = new javax.swing.JLabel();
        lblPid3 = new javax.swing.JLabel();
        lblCpu4 = new javax.swing.JLabel();
        lblCpu2 = new javax.swing.JLabel();
        lblPid1 = new javax.swing.JLabel();
        lblPid4 = new javax.swing.JLabel();
        lblCpu1 = new javax.swing.JLabel();
        lblRam1 = new javax.swing.JLabel();
        lblRam4 = new javax.swing.JLabel();
        lblRam3 = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        lblNome2 = new javax.swing.JLabel();
        lblNome4 = new javax.swing.JLabel();
        lblNome3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblcpuFrequencia = new javax.swing.JLabel();
        lblFrequenciaMaxCpu = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblCpuProcessor = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblCpuUso = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblDiscoUso = new javax.swing.JLabel();
        lblParticaoLivre = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblDiscoTotal = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblDiscoNome = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lblMemoriaTotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblMemoriaUso = new javax.swing.JLabel();
        lblMemoriaTeste = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(61, 63, 66));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(61, 63, 66));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pesquisa de satisfação");
        jLabel5.setToolTipText("");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 220, 40));

        jLabel6.setBackground(new java.awt.Color(46, 43, 43));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Dashboard");
        jLabel6.setToolTipText("");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 220, 40));

        jLabel7.setBackground(new java.awt.Color(61, 63, 66));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Máquina nova");
        jLabel7.setToolTipText("");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 220, 40));

        jLabel8.setBackground(new java.awt.Color(61, 63, 66));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Configurações");
        jLabel8.setToolTipText("");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 220, 50));

        jLabel9.setBackground(new java.awt.Color(61, 63, 66));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("FAQ's");
        jLabel9.setToolTipText("");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, 40));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, 670));

        jPanel3.setBackground(new java.awt.Color(242, 106, 22));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(244, 147, 88));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("  Novo");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setOpaque(true);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 110, 20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 60, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Admistrador");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, 80, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 70, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1470, 40));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(243, 122, 23));
        jLabel10.setText("DASHBOARD");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1230, 20));

        btnAnalisarComponentes.setBackground(new java.awt.Color(242, 106, 22));
        btnAnalisarComponentes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAnalisarComponentes.setForeground(new java.awt.Color(255, 255, 255));
        btnAnalisarComponentes.setText("Analisar componentes");
        btnAnalisarComponentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisarComponentesActionPerformed(evt);
            }
        });
        jPanel4.add(btnAnalisarComponentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 300, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(242, 106, 22));
        jLabel13.setText("PROCESSOS");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("PID");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("NOME");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("%CPU");
        jLabel17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("%MEM");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setToolTipText("");
        jSeparator2.setAutoscrolls(true);
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jSeparator2.setInheritsPopupMenu(true);
        jSeparator2.setMaximumSize(new java.awt.Dimension(32767, 4000));
        jSeparator2.setPreferredSize(new java.awt.Dimension(100, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setToolTipText("");
        jSeparator3.setAutoscrolls(true);
        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jSeparator3.setInheritsPopupMenu(true);
        jSeparator3.setMaximumSize(new java.awt.Dimension(32767, 4000));
        jSeparator3.setPreferredSize(new java.awt.Dimension(100, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setToolTipText("");
        jSeparator4.setAutoscrolls(true);
        jSeparator4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jSeparator4.setInheritsPopupMenu(true);
        jSeparator4.setMaximumSize(new java.awt.Dimension(32767, 4000));
        jSeparator4.setPreferredSize(new java.awt.Dimension(100, 10));

        lblRam2.setBackground(new java.awt.Color(255, 255, 255));
        lblRam2.setOpaque(true);

        lblPid2.setBackground(new java.awt.Color(255, 255, 255));
        lblPid2.setOpaque(true);

        lblCpu3.setBackground(new java.awt.Color(255, 255, 255));
        lblCpu3.setOpaque(true);

        lblPid3.setBackground(new java.awt.Color(255, 255, 255));
        lblPid3.setOpaque(true);

        lblCpu4.setBackground(new java.awt.Color(255, 255, 255));
        lblCpu4.setOpaque(true);

        lblCpu2.setBackground(new java.awt.Color(255, 255, 255));
        lblCpu2.setOpaque(true);

        lblPid1.setBackground(new java.awt.Color(255, 255, 255));

        lblPid4.setBackground(new java.awt.Color(255, 255, 255));
        lblPid4.setOpaque(true);

        lblCpu1.setBackground(new java.awt.Color(255, 255, 255));
        lblCpu1.setOpaque(true);

        lblRam1.setBackground(new java.awt.Color(255, 255, 255));
        lblRam1.setOpaque(true);

        lblRam4.setBackground(new java.awt.Color(255, 255, 255));
        lblRam4.setOpaque(true);

        lblRam3.setBackground(new java.awt.Color(255, 255, 255));
        lblRam3.setOpaque(true);

        lblNome1.setBackground(new java.awt.Color(255, 255, 255));
        lblNome1.setOpaque(true);

        lblNome2.setBackground(new java.awt.Color(255, 255, 255));
        lblNome2.setOpaque(true);

        lblNome4.setBackground(new java.awt.Color(255, 255, 255));
        lblNome4.setOpaque(true);

        lblNome3.setBackground(new java.awt.Color(255, 255, 255));
        lblNome3.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel15))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPid1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPid3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPid2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPid4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCpu1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(lblCpu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCpu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCpu4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblRam2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRam1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRam4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRam3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel18)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(147, 147, 147))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                                        .addComponent(lblPid1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblPid2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblPid3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblPid4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                                        .addComponent(lblCpu1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblCpu2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblCpu3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblCpu4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(lblRam1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblRam2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                                .addComponent(lblRam3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblRam4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26))))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNome4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 410, 250));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcpuFrequencia.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblcpuFrequencia.setText("0.0 GHz");
        lblcpuFrequencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel10.add(lblcpuFrequencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 80, 40));

        lblFrequenciaMaxCpu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblFrequenciaMaxCpu.setText("0.0 GHz");
        jPanel10.add(lblFrequenciaMaxCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(242, 106, 22));
        jLabel19.setText("Modelo:");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(242, 106, 22));
        jLabel14.setText("CPU");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, 20));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(242, 106, 22));
        jLabel24.setText("Uso de CPU:");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(242, 106, 22));
        jLabel25.setText("Uso de CPU em GiB:");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lblCpuProcessor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCpuProcessor.setText("?");
        jPanel10.add(lblCpuProcessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 360, 50));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(242, 106, 22));
        jLabel28.setText("Frequência atual:");
        jPanel10.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblCpuUso.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCpuUso.setText("0%");
        lblCpuUso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel10.add(lblCpuUso, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 80, 40));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 400, 260));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(242, 106, 22));
        jLabel11.setText("DISCO");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 60, 40));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(242, 106, 22));
        jLabel20.setText("Nome:");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        lblDiscoUso.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDiscoUso.setText("0%");
        jPanel5.add(lblDiscoUso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        lblParticaoLivre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblParticaoLivre.setText("0.0 GiB");
        jPanel5.add(lblParticaoLivre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(242, 106, 22));
        jLabel26.setText("Partição livre:");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(242, 106, 22));
        jLabel27.setText("Partição total:");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        lblDiscoTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDiscoTotal.setText("0.0 GiB");
        jPanel5.add(lblDiscoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(242, 106, 22));
        jLabel29.setText("Disco em uso: ");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        lblDiscoNome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDiscoNome.setText("?");
        jPanel5.add(lblDiscoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 230, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 400, 250));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMemoriaTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMemoriaTotal.setText("0.0 GiB");
        lblMemoriaTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel11.add(lblMemoriaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 70, 40));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(242, 106, 22));
        jLabel12.setText("MEMÓRIA RAM");
        jPanel11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, 20));

        lblMemoriaUso.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMemoriaUso.setText("0%");
        jPanel11.add(lblMemoriaUso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, 20));

        lblMemoriaTeste.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMemoriaTeste.setText("0.0 GiB");
        lblMemoriaTeste.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel11.add(lblMemoriaTeste, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 70, 40));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(242, 106, 22));
        jLabel21.setText("Memória Disponível:");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(242, 106, 22));
        jLabel22.setText("Memória usada em GiB:");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(242, 106, 22));
        jLabel23.setText("Memória em uso:");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 410, 260));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 990, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalisarComponentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisarComponentesActionPerformed
         try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

        //cria uma a��o, e essa a��o escreve na tela
        ActionListener action = (ActionEvent actionEvent) -> {
            lblMemoriaTeste.setText(String.format("%.2fGhz", cpu.getCurrentFrequency()));
            lblcpuFrequencia.setText(String.format("%.2fGhz", cpu.getFrequency()));
            lblCpuUso.setText(String.format("%.1f%%", cpu.getCurrentPercent()));

            lblMemoriaTotal.setText(String.format("%.2fGB", ram.getUsedMemory()));
            lblMemoriaTeste.setText(String.format("%.2fGB", ram.getAvailableMemory()));
            lblMemoriaUso.setText(String.format("%.1f%%", ram.getCurrentPercent()));

            lblDiscoNome.setText(disk.getName(0));
            lblDiscoTotal.setText(String.format("%.2fGB", disk.getDiskSize(0)));
            lblParticaoLivre.setText(String.format("%.2fGB", disk.getFreeSize(0)));
            lblDiscoUso.setText(String.format("%.1f%%", disk.getDiskSize(0)));
            

        };
        
        
//        Double cpuFrequencia = componentes.cpuFrequencia();
//        lblcpuFrequencia.setText(String.format("%.2f GHz", cpuFrequencia));
//
//        lblFrequenciaMaxCpu.setText(String.format("%.2f GHz", componentes.frequenciaMaxCpu()));
//
//        Double disponivelMemoria = componentes.disponivelMemoria();
//        lblMemoriaTeste.setText(String.format("%.1f GiB", disponivelMemoria));
//
//        Double totalMemoria = componentes.totalMemoria();
//        lblMemoriaTotal.setText(String.format("%.1f GiB", totalMemoria));
//
//        Double usoMemoria = componentes.usoMemoria();
//        lblMemoriaUso.setText(String.format("%.1f%%", usoMemoria));
//        
//        
//        //Criei um Array (Vetor) para ele listar 4 processos que está no OshiConsole
//        List arrayProcessos[] = new ArrayList[4];
//        arrayProcessos = componentes.processoLista();
//        
//        for (int i = 0; i < 4; i++) {
//            //Switch case eh quando ele observa a variável e quando for verdadeiro (true)
//            //Ele irá executar, o ganho de performece é muito melhor 
//            //O if e else ficaria repetindo várias vezes, fazendo que o fique defasado
//            
//            switch (i) {
//                case 0:
//                    lblPid1.setText(String.format("%d", arrayProcessos[i].get(0)));
//                    lblCpu1.setText(String.format("%.2f", arrayProcessos[i].get(1)));
//                    lblRam1.setText(String.format("%.2f", arrayProcessos[i].get(2)));
//                    lblNome1.setText(String.format("%s", arrayProcessos[i].get(3)));
//                    break;
//                case 1:
//                    lblPid2.setText(String.format("%d", arrayProcessos[i].get(0)));
//                    lblCpu2.setText(String.format("%.2f", arrayProcessos[i].get(1)));
//                    lblRam2.setText(String.format("%.2f", arrayProcessos[i].get(2)));
//                    lblNome2.setText(String.format("%s", arrayProcessos[i].get(3)));
//                    break;
//                case 2:
//                    lblPid3.setText(String.format("%d", arrayProcessos[i].get(0)));
//                    lblCpu3.setText(String.format("%.2f", arrayProcessos[i].get(1)));
//                    lblRam3.setText(String.format("%.2f", arrayProcessos[i].get(2)));
//                    lblNome3.setText(String.format("%s", arrayProcessos[i].get(3)));
//                    break;
//                case 3:
//                    lblPid4.setText(String.format("%d", arrayProcessos[i].get(0)));
//                    lblCpu4.setText(String.format("%.2f", arrayProcessos[i].get(1)));
//                    lblRam4.setText(String.format("%.2f", arrayProcessos[i].get(2)));
//                    lblNome4.setText(String.format("%s", arrayProcessos[i].get(3)));
//                    break;
//        }
//    }
//        
//      Double livreParticao = componentes.usoDiscoParticipacao();
//      lblParticaoLivre.setText(String.format("%.2f GiB",livreParticao));
//      
//      Double totalDisco = componentes.usoDiscoTotal();
//      lblDiscoTotal.setText(String.format("%.2f GiB", totalDisco));
//      
//      Double usoDisco = (100 -((livreParticao / totalDisco) * 100));
//      lblDiscoUso.setText(String.format("%.2f%%", usoDisco));
//      
//      String cpuProcessor = componentes.cpuProcessor();
//      lblCpuProcessor.setText(String.format("%s\n",cpuProcessor));
    }//GEN-LAST:event_btnAnalisarComponentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalisarComponentes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblCpu1;
    private javax.swing.JLabel lblCpu2;
    private javax.swing.JLabel lblCpu3;
    private javax.swing.JLabel lblCpu4;
    private javax.swing.JLabel lblCpuProcessor;
    private javax.swing.JLabel lblCpuUso;
    private javax.swing.JLabel lblDiscoNome;
    private javax.swing.JLabel lblDiscoTotal;
    private javax.swing.JLabel lblDiscoUso;
    private javax.swing.JLabel lblFrequenciaMaxCpu;
    private javax.swing.JLabel lblMemoriaTeste;
    private javax.swing.JLabel lblMemoriaTotal;
    private javax.swing.JLabel lblMemoriaUso;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblNome3;
    private javax.swing.JLabel lblNome4;
    private javax.swing.JLabel lblParticaoLivre;
    private javax.swing.JLabel lblPid1;
    private javax.swing.JLabel lblPid2;
    private javax.swing.JLabel lblPid3;
    private javax.swing.JLabel lblPid4;
    private javax.swing.JLabel lblRam1;
    private javax.swing.JLabel lblRam2;
    private javax.swing.JLabel lblRam3;
    private javax.swing.JLabel lblRam4;
    private javax.swing.JLabel lblcpuFrequencia;
    // End of variables declaration//GEN-END:variables
}
